function tvRP.getNearestVehicles(radius)
	local r = {}
	local px,py,pz = table.unpack(GetEntityCoords(PlayerPedId()))

	local vehs = {}
	local it,veh = FindFirstVehicle()
	if veh then
		table.insert(vehs,veh)
	end
	local ok
	repeat
		ok,veh = FindNextVehicle(it)
		if ok and veh then
			table.insert(vehs,veh)
		end
	until not ok
	EndFindVehicle(it)

	for _,veh in pairs(vehs) do
		local x,y,z = table.unpack(GetEntityCoords(veh))
		local distance = Vdist(x,y,z,px,py,pz)
		if distance <= radius then
			r[veh] = distance
		end
	end
	return r
end

function tvRP.getNearestVehicle(radius)
	local veh
	local vehs = tvRP.getNearestVehicles(radius)
	local min = radius+0.0001
	for _veh,dist in pairs(vehs) do
		if dist < min then
			min = dist
			veh = _veh
		end
	end
	return veh 
end

function tvRP.ejectVehicle()
	local ped = PlayerPedId()
	if IsPedSittingInAnyVehicle(ped) then
		TaskLeaveVehicle(ped,GetVehiclePedIsIn(ped),4160)
	end
end

function tvRP.isInVehicle()
	return IsPedSittingInAnyVehicle(PlayerPedId())
end

function tvRP.GetVehicleSeat()
    return GetPedInVehicleSeat(GetVehiclePedIsUsing(PlayerPedId()),-1) == PlayerPedId()
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
local vehList = {
    -- Boats = Barcos
    { ['name'] = "dinghy", ['hash'] = GetHashKey('dinghy'), ["banned"] = false },
    { ['name'] = "dinghy2", ['hash'] = GetHashKey('dinghy2'), ["banned"] = false },
    { ['name'] = "dinghy3", ['hash'] = GetHashKey('dinghy3'), ["banned"] = false },
    { ['name'] = "dinghy4", ['hash'] = GetHashKey('dinghy4'), ["banned"] = false },
    { ['name'] = "jetmax", ['hash'] = GetHashKey('jetmax'), ["banned"] = false },
    { ['name'] = "marquis", ['hash'] = GetHashKey('marquis'), ["banned"] = false },
    { ['name'] = "seashark", ['hash'] = GetHashKey('seashark'), ["banned"] = false },
    { ['name'] = "seashark2", ['hash'] = GetHashKey('seashark2'), ["banned"] = false },
    { ['name'] = "seashark3", ['hash'] = GetHashKey('seashark3'), ["banned"] = false },
    { ['name'] = "speeder", ['hash'] = GetHashKey('speeder'), ["banned"] = false },
    { ['name'] = "speeder2", ['hash'] = GetHashKey('speeder2'), ["banned"] = false },
    { ['name'] = "squalo", ['hash'] = GetHashKey('squalo'), ["banned"] = false },
    { ['name'] = "submersible", ['hash'] = GetHashKey('submersible'), ["banned"] = false },
    { ['name'] = "submersible2", ['hash'] = GetHashKey('submersible2'), ["banned"] = false },
    { ['name'] = "suntrap", ['hash'] = GetHashKey('suntrap'), ["banned"] = false },
    { ['name'] = "toro", ['hash'] = GetHashKey('toro'), ["banned"] = false },
    { ['name'] = "toro2", ['hash'] = GetHashKey('toro2'), ["banned"] = false },
    { ['name'] = "tropic", ['hash'] = GetHashKey('tropic'), ["banned"] = false },
    { ['name'] = "tropic2", ['hash'] = GetHashKey('tropic2'), ["banned"] = false },
    { ['name'] = "tug", ['hash'] = GetHashKey('tug'), ["banned"] = false },
    { ['name'] = "avisa", ['hash'] = GetHashKey('avisa'), ["banned"] = false },
    { ['name'] = "dinghy5", ['hash'] = GetHashKey('dinghy5'), ["banned"] = false },
    { ['name'] = "kosatka", ['hash'] = GetHashKey('kosatka'), ["banned"] = false },
    { ['name'] = "longfin", ['hash'] = GetHashKey('longfin'), ["banned"] = false },
    { ['name'] = "patrolboat", ['hash'] = GetHashKey('patrolboat'), ["banned"] = false },
    -- Commercials = Veículos Comerciais
    { ['name'] = "benson", ['hash'] = GetHashKey('benson'), ["banned"] = false },
    { ['name'] = "biff", ['hash'] = GetHashKey('biff'), ["banned"] = false },
    { ['name'] = "cerberus", ['hash'] = GetHashKey('cerberus'), ["banned"] = false },
    { ['name'] = "cerberus2", ['hash'] = GetHashKey('cerberus2'), ["banned"] = false },
    { ['name'] = "cerberus3", ['hash'] = GetHashKey('cerberus3'), ["banned"] = false },
    { ['name'] = "hauler", ['hash'] = GetHashKey('hauler'), ["banned"] = false },
    { ['name'] = "hauler2", ['hash'] = GetHashKey('hauler2'), ["banned"] = false },
    { ['name'] = "mule", ['hash'] = GetHashKey('mule'), ["banned"] = false },
    { ['name'] = "mule2", ['hash'] = GetHashKey('mule2'), ["banned"] = false },
    { ['name'] = "mule3", ['hash'] = GetHashKey('mule3'), ["banned"] = false },
    { ['name'] = "mule4", ['hash'] = GetHashKey('mule4'), ["banned"] = false },
    { ['name'] = "packer", ['hash'] = GetHashKey('packer'), ["banned"] = false },
    { ['name'] = "phantom", ['hash'] = GetHashKey('phantom'), ["banned"] = false },
    { ['name'] = "phantom2", ['hash'] = GetHashKey('phantom2'), ["banned"] = false },
    { ['name'] = "phantom3", ['hash'] = GetHashKey('phantom3'), ["banned"] = false },
    { ['name'] = "pounder", ['hash'] = GetHashKey('pounder'), ["banned"] = false },
    { ['name'] = "pounder2", ['hash'] = GetHashKey('pounder2'), ["banned"] = false },
    { ['name'] = "stockade", ['hash'] = GetHashKey('stockade'), ["banned"] = false },
    { ['name'] = "stockade3", ['hash'] = GetHashKey('stockade3'), ["banned"] = false },
    { ['name'] = "terbyte", ['hash'] = GetHashKey('terbyte'), ["banned"] = false },
    -- Compacts = Veículos Compactos
    { ['name'] = "asbo", ['hash'] = GetHashKey('asbo'), ["banned"] = false },
    { ['name'] = "blista", ['hash'] = GetHashKey('blista'), ["banned"] = false },
    { ['name'] = "brioso", ['hash'] = GetHashKey('brioso'), ["banned"] = false },
    { ['name'] = "club", ['hash'] = GetHashKey('club'), ["banned"] = false },
    { ['name'] = "dilettante", ['hash'] = GetHashKey('dilettante'), ["banned"] = false },
    { ['name'] = "dilettante2", ['hash'] = GetHashKey('dilettante2'), ["banned"] = false },
    { ['name'] = "kanjo", ['hash'] = GetHashKey('kanjo'), ["banned"] = false },
    { ['name'] = "issi2", ['hash'] = GetHashKey('issi2'), ["banned"] = false },
    { ['name'] = "issi3", ['hash'] = GetHashKey('issi3'), ["banned"] = false },
    { ['name'] = "issi4", ['hash'] = GetHashKey('issi4'), ["banned"] = false },
    { ['name'] = "issi5", ['hash'] = GetHashKey('issi5'), ["banned"] = false },
    { ['name'] = "issi6", ['hash'] = GetHashKey('issi6'), ["banned"] = false },
    { ['name'] = "panto", ['hash'] = GetHashKey('panto'), ["banned"] = false },
    { ['name'] = "prairie", ['hash'] = GetHashKey('prairie'), ["banned"] = false },
    { ['name'] = "rhapsody", ['hash'] = GetHashKey('rhapsody'), ["banned"] = false },
    { ['name'] = "brioso2", ['hash'] = GetHashKey('brioso2'), ["banned"] = false },
    { ['name'] = "weevil", ['hash'] = GetHashKey('weevil'), ["banned"] = false },
    -- Coupes = Coupé
    { ['name'] = "cogcabrio", ['hash'] = GetHashKey('cogcabrio'), ["banned"] = false },
    { ['name'] = "exemplar", ['hash'] = GetHashKey('exemplar'), ["banned"] = false },
    { ['name'] = "f620", ['hash'] = GetHashKey('f620'), ["banned"] = false },
    { ['name'] = "felon", ['hash'] = GetHashKey('felon'), ["banned"] = false },
    { ['name'] = "felon2", ['hash'] = GetHashKey('felon2'), ["banned"] = false },
    { ['name'] = "jackal", ['hash'] = GetHashKey('jackal'), ["banned"] = false },
    { ['name'] = "oracle", ['hash'] = GetHashKey('oracle'), ["banned"] = false },
    { ['name'] = "oracle2", ['hash'] = GetHashKey('oracle2'), ["banned"] = false },
    { ['name'] = "sentinel", ['hash'] = GetHashKey('sentinel'), ["banned"] = false },
    { ['name'] = "sentinel2", ['hash'] = GetHashKey('sentinel2'), ["banned"] = false },
    { ['name'] = "windsor", ['hash'] = GetHashKey('windsor'), ["banned"] = false },
    { ['name'] = "windsor2", ['hash'] = GetHashKey('windsor2'), ["banned"] = false },
    { ['name'] = "zion", ['hash'] = GetHashKey('zion'), ["banned"] = false },
    { ['name'] = "zion2", ['hash'] = GetHashKey('zion2'), ["banned"] = false },
    -- Cycles = Bicicletas
    { ['name'] = "bmx", ['hash'] = GetHashKey('bmx'), ["banned"] = false },
    { ['name'] = "cruiser", ['hash'] = GetHashKey('cruiser'), ["banned"] = false },
    { ['name'] = "fixter", ['hash'] = GetHashKey('fixter'), ["banned"] = false },
    { ['name'] = "scorcher", ['hash'] = GetHashKey('scorcher'), ["banned"] = false },
    { ['name'] = "tribike", ['hash'] = GetHashKey('tribike'), ["banned"] = false },
    { ['name'] = "tribike2", ['hash'] = GetHashKey('tribike2'), ["banned"] = false },
    { ['name'] = "tribike3", ['hash'] = GetHashKey('tribike3'), ["banned"] = false },
    -- Emergency = Emergencia
    { ['name'] = "ambulance", ['hash'] = GetHashKey('ambulance'), ["banned"] = false },
    { ['name'] = "fbi", ['hash'] = GetHashKey('fbi'), ["banned"] = false },
    { ['name'] = "fbi2", ['hash'] = GetHashKey('fbi2'), ["banned"] = false },
    { ['name'] = "firetruk", ['hash'] = GetHashKey('firetruk'), ["banned"] = false },
    { ['name'] = "lguard", ['hash'] = GetHashKey('lguard'), ["banned"] = false },
    { ['name'] = "pbus", ['hash'] = GetHashKey('pbus'), ["banned"] = false },
    { ['name'] = "police", ['hash'] = GetHashKey('police'), ["banned"] = false },
    { ['name'] = "police2", ['hash'] = GetHashKey('police2'), ["banned"] = false },
    { ['name'] = "police3", ['hash'] = GetHashKey('police3'), ["banned"] = false },
    { ['name'] = "police4", ['hash'] = GetHashKey('police4'), ["banned"] = false },
    { ['name'] = "policeb", ['hash'] = GetHashKey('policeb'), ["banned"] = false },
    { ['name'] = "polmav", ['hash'] = GetHashKey('polmav'), ["banned"] = false },
    { ['name'] = "policeold1", ['hash'] = GetHashKey('policeold1'), ["banned"] = false },
    { ['name'] = "policeold2", ['hash'] = GetHashKey('policeold2'), ["banned"] = false },
    { ['name'] = "policet", ['hash'] = GetHashKey('policet'), ["banned"] = false },
    { ['name'] = "pranger", ['hash'] = GetHashKey('pranger'), ["banned"] = false },
    { ['name'] = "predator", ['hash'] = GetHashKey('predator'), ["banned"] = false },
    { ['name'] = "riot", ['hash'] = GetHashKey('riot'), ["banned"] = false },
    { ['name'] = "riot2", ['hash'] = GetHashKey('riot2'), ["banned"] = false },
    { ['name'] = "sheriff", ['hash'] = GetHashKey('sheriff'), ["banned"] = false },
    { ['name'] = "sheriff2", ['hash'] = GetHashKey('sheriff2'), ["banned"] = false },
    -- Helicopters = Helicópteros
    { ['name'] = "akula", ['hash'] = GetHashKey('akula'), ["banned"] = false },
    { ['name'] = "annihilator", ['hash'] = GetHashKey('annihilator'), ["banned"] = false },
    { ['name'] = "buzzard", ['hash'] = GetHashKey('buzzard'), ["banned"] = false },
    { ['name'] = "buzzard2", ['hash'] = GetHashKey('buzzard2'), ["banned"] = false },
    { ['name'] = "cargobob", ['hash'] = GetHashKey('cargobob'), ["banned"] = false },
    { ['name'] = "cargobob2", ['hash'] = GetHashKey('cargobob2'), ["banned"] = false },
    { ['name'] = "cargobob3", ['hash'] = GetHashKey('cargobob3'), ["banned"] = false },
    { ['name'] = "cargobob4", ['hash'] = GetHashKey('cargobob4'), ["banned"] = false },
    { ['name'] = "frogger", ['hash'] = GetHashKey('frogger'), ["banned"] = false },
    { ['name'] = "frogger2", ['hash'] = GetHashKey('frogger2'), ["banned"] = false },
    { ['name'] = "havok", ['hash'] = GetHashKey('havok'), ["banned"] = false },
    { ['name'] = "hunter", ['hash'] = GetHashKey('hunter'), ["banned"] = false },
    { ['name'] = "maverick", ['hash'] = GetHashKey('maverick'), ["banned"] = false },
    { ['name'] = "savage", ['hash'] = GetHashKey('savage'), ["banned"] = false },
    { ['name'] = "seasparrow", ['hash'] = GetHashKey('seasparrow'), ["banned"] = false },
    { ['name'] = "skylift", ['hash'] = GetHashKey('skylift'), ["banned"] = false },
    { ['name'] = "supervolito", ['hash'] = GetHashKey('supervolito'), ["banned"] = false },
    { ['name'] = "supervolito2", ['hash'] = GetHashKey('supervolito2'), ["banned"] = false },
    { ['name'] = "swift", ['hash'] = GetHashKey('swift'), ["banned"] = false },
    { ['name'] = "swift2", ['hash'] = GetHashKey('swift2'), ["banned"] = false },
    { ['name'] = "valkyrie", ['hash'] = GetHashKey('valkyrie'), ["banned"] = false },
    { ['name'] = "valkyrie2", ['hash'] = GetHashKey('valkyrie2'), ["banned"] = false },
    { ['name'] = "volatus", ['hash'] = GetHashKey('volatus'), ["banned"] = false },
    { ['name'] = "annihilator2", ['hash'] = GetHashKey('annihilator2'), ["banned"] = false },
    { ['name'] = "seasparrow2", ['hash'] = GetHashKey('seasparrow2'), ["banned"] = false },
    { ['name'] = "seasparrow3", ['hash'] = GetHashKey('seasparrow3'), ["banned"] = false },
    -- Industrial = Industriais
    { ['name'] = "bulldozer", ['hash'] = GetHashKey('bulldozer'), ["banned"] = false },
    { ['name'] = "cutter", ['hash'] = GetHashKey('cutter'), ["banned"] = false },
    { ['name'] = "dump", ['hash'] = GetHashKey('dump'), ["banned"] = false },
    { ['name'] = "flatbed", ['hash'] = GetHashKey('flatbed'), ["banned"] = false },
    { ['name'] = "guardian", ['hash'] = GetHashKey('guardian'), ["banned"] = false },
    { ['name'] = "handler", ['hash'] = GetHashKey('handler'), ["banned"] = false },
    { ['name'] = "mixer", ['hash'] = GetHashKey('mixer'), ["banned"] = false },
    { ['name'] = "mixer2", ['hash'] = GetHashKey('mixer2'), ["banned"] = false },
    { ['name'] = "rubble", ['hash'] = GetHashKey('rubble'), ["banned"] = false },
    { ['name'] = "tiptruck", ['hash'] = GetHashKey('tiptruck'), ["banned"] = false },
    { ['name'] = "tiptruck2", ['hash'] = GetHashKey('tiptruck2'), ["banned"] = false },
    -- Military = Militares
    { ['name'] = "apc", ['hash'] = GetHashKey('apc'), ["banned"] = false },
    { ['name'] = "barracks", ['hash'] = GetHashKey('barracks'), ["banned"] = false },
    { ['name'] = "barracks2", ['hash'] = GetHashKey('barracks2'), ["banned"] = false },
    { ['name'] = "barracks3", ['hash'] = GetHashKey('barracks3'), ["banned"] = false },
    { ['name'] = "barrage", ['hash'] = GetHashKey('barrage'), ["banned"] = false },
    { ['name'] = "chernobog", ['hash'] = GetHashKey('chernobog'), ["banned"] = false },
    { ['name'] = "crusader", ['hash'] = GetHashKey('crusader'), ["banned"] = false },
    { ['name'] = "halftrack", ['hash'] = GetHashKey('halftrack'), ["banned"] = false },
    { ['name'] = "khanjali", ['hash'] = GetHashKey('khanjali'), ["banned"] = false },
    { ['name'] = "minitank", ['hash'] = GetHashKey('minitank'), ["banned"] = false },
    { ['name'] = "rhino", ['hash'] = GetHashKey('rhino'), ["banned"] = false },
    { ['name'] = "scarab", ['hash'] = GetHashKey('scarab'), ["banned"] = false },
    { ['name'] = "scarab2", ['hash'] = GetHashKey('scarab2'), ["banned"] = false },
    { ['name'] = "scarab3", ['hash'] = GetHashKey('scarab3'), ["banned"] = false },
    { ['name'] = "thruster", ['hash'] = GetHashKey('thruster'), ["banned"] = false },
    { ['name'] = "trailersmall2", ['hash'] = GetHashKey('trailersmall2'), ["banned"] = false },
    { ['name'] = "vetir", ['hash'] = GetHashKey('vetir'), ["banned"] = false },
    -- Motorcycles = Motos
    { ['name'] = "akuma", ['hash'] = GetHashKey('akuma'), ["banned"] = false },
    { ['name'] = "avarus", ['hash'] = GetHashKey('avarus'), ["banned"] = false },
    { ['name'] = "bagger", ['hash'] = GetHashKey('bagger'), ["banned"] = false },
    { ['name'] = "bati", ['hash'] = GetHashKey('bati'), ["banned"] = false },
    { ['name'] = "bati2", ['hash'] = GetHashKey('bati2'), ["banned"] = false },
    { ['name'] = "bf400", ['hash'] = GetHashKey('bf400'), ["banned"] = false },
    { ['name'] = "carbonrs", ['hash'] = GetHashKey('carbonrs'), ["banned"] = false },
    { ['name'] = "chimera", ['hash'] = GetHashKey('chimera'), ["banned"] = false },
    { ['name'] = "cliffhanger", ['hash'] = GetHashKey('cliffhanger'), ["banned"] = false },
    { ['name'] = "daemon", ['hash'] = GetHashKey('daemon'), ["banned"] = false },
    { ['name'] = "daemon2", ['hash'] = GetHashKey('daemon2'), ["banned"] = false },
    { ['name'] = "defiler", ['hash'] = GetHashKey('defiler'), ["banned"] = false },
    { ['name'] = "deathbike", ['hash'] = GetHashKey('deathbike'), ["banned"] = false },
    { ['name'] = "deathbike2", ['hash'] = GetHashKey('deathbike2'), ["banned"] = false },
    { ['name'] = "deathbike3", ['hash'] = GetHashKey('deathbike3'), ["banned"] = false },
    { ['name'] = "diablous", ['hash'] = GetHashKey('diablous'), ["banned"] = false },
    { ['name'] = "diablous2", ['hash'] = GetHashKey('diablous2'), ["banned"] = false },
    { ['name'] = "double", ['hash'] = GetHashKey('double'), ["banned"] = false },
    { ['name'] = "enduro", ['hash'] = GetHashKey('enduro'), ["banned"] = false },
    { ['name'] = "esskey", ['hash'] = GetHashKey('esskey'), ["banned"] = false },
    { ['name'] = "faggio", ['hash'] = GetHashKey('faggio'), ["banned"] = false },
    { ['name'] = "faggio2", ['hash'] = GetHashKey('faggio2'), ["banned"] = false },
    { ['name'] = "faggio3", ['hash'] = GetHashKey('faggio3'), ["banned"] = false },
    { ['name'] = "fcr", ['hash'] = GetHashKey('fcr'), ["banned"] = false },
    { ['name'] = "fcr2", ['hash'] = GetHashKey('fcr2'), ["banned"] = false },
    { ['name'] = "gargoyle", ['hash'] = GetHashKey('gargoyle'), ["banned"] = false },
    { ['name'] = "hakuchou", ['hash'] = GetHashKey('hakuchou'), ["banned"] = false },
    { ['name'] = "hakuchou2", ['hash'] = GetHashKey('hakuchou2'), ["banned"] = false },
    { ['name'] = "hexer", ['hash'] = GetHashKey('hexer'), ["banned"] = false },
    { ['name'] = "innovation", ['hash'] = GetHashKey('innovation'), ["banned"] = false },
    { ['name'] = "lectro", ['hash'] = GetHashKey('lectro'), ["banned"] = false },
    { ['name'] = "manchez", ['hash'] = GetHashKey('manchez'), ["banned"] = false },
    { ['name'] = "nemesis", ['hash'] = GetHashKey('nemesis'), ["banned"] = false },
    { ['name'] = "nightblade", ['hash'] = GetHashKey('nightblade'), ["banned"] = false },
    { ['name'] = "oppressor", ['hash'] = GetHashKey('oppressor'), ["banned"] = false },
    { ['name'] = "oppressor2", ['hash'] = GetHashKey('oppressor2'), ["banned"] = false },
    { ['name'] = "pcj", ['hash'] = GetHashKey('pcj'), ["banned"] = false },
    { ['name'] = "ratbike", ['hash'] = GetHashKey('ratbike'), ["banned"] = false },
    { ['name'] = "rrocket", ['hash'] = GetHashKey('rrocket'), ["banned"] = false },
    { ['name'] = "sanchez", ['hash'] = GetHashKey('sanchez'), ["banned"] = false },
    { ['name'] = "sanchez2", ['hash'] = GetHashKey('sanchez2'), ["banned"] = false },
    { ['name'] = "sanctus", ['hash'] = GetHashKey('sanctus'), ["banned"] = false },
    { ['name'] = "shotaro", ['hash'] = GetHashKey('shotaro'), ["banned"] = false },
    { ['name'] = "sovereign", ['hash'] = GetHashKey('sovereign'), ["banned"] = false },
    { ['name'] = "stryder", ['hash'] = GetHashKey('stryder'), ["banned"] = false },
    { ['name'] = "thrust", ['hash'] = GetHashKey('thrust'), ["banned"] = false },
    { ['name'] = "vader", ['hash'] = GetHashKey('vader'), ["banned"] = false },
    { ['name'] = "vindicator", ['hash'] = GetHashKey('vindicator'), ["banned"] = false },
    { ['name'] = "vortex", ['hash'] = GetHashKey('vortex'), ["banned"] = false },
    { ['name'] = "wolfsbane", ['hash'] = GetHashKey('wolfsbane'), ["banned"] = false },
    { ['name'] = "zombiea", ['hash'] = GetHashKey('zombiea'), ["banned"] = false },
    { ['name'] = "zombieb", ['hash'] = GetHashKey('zombieb'), ["banned"] = false },
    { ['name'] = "manchez2", ['hash'] = GetHashKey('manchez2'), ["banned"] = false },
    -- Muscle = Clássicos
    { ['name'] = "blade", ['hash'] = GetHashKey('blade'), ["banned"] = false },
    { ['name'] = "buccaneer", ['hash'] = GetHashKey('buccaneer'), ["banned"] = false },
    { ['name'] = "buccaneer2", ['hash'] = GetHashKey('buccaneer2'), ["banned"] = false },
    { ['name'] = "chino", ['hash'] = GetHashKey('chino'), ["banned"] = false },
    { ['name'] = "chino2", ['hash'] = GetHashKey('chino2'), ["banned"] = false },
    { ['name'] = "clique", ['hash'] = GetHashKey('clique'), ["banned"] = false },
    { ['name'] = "coquette3", ['hash'] = GetHashKey('coquette3'), ["banned"] = false },
    { ['name'] = "deviant", ['hash'] = GetHashKey('deviant'), ["banned"] = false },
    { ['name'] = "dominator", ['hash'] = GetHashKey('dominator'), ["banned"] = false },
    { ['name'] = "dominator2", ['hash'] = GetHashKey('dominator2'), ["banned"] = false },
    { ['name'] = "dominator3", ['hash'] = GetHashKey('dominator3'), ["banned"] = false },
    { ['name'] = "dominator4", ['hash'] = GetHashKey('dominator4'), ["banned"] = false },
    { ['name'] = "dominator5", ['hash'] = GetHashKey('dominator5'), ["banned"] = false },
    { ['name'] = "dominator6", ['hash'] = GetHashKey('dominator6'), ["banned"] = false },
    { ['name'] = "dukes", ['hash'] = GetHashKey('dukes'), ["banned"] = false },
    { ['name'] = "dukes2", ['hash'] = GetHashKey('dukes2'), ["banned"] = false },
    { ['name'] = "dukes3", ['hash'] = GetHashKey('dukes3'), ["banned"] = false },
    { ['name'] = "faction", ['hash'] = GetHashKey('faction'), ["banned"] = false },
    { ['name'] = "faction2", ['hash'] = GetHashKey('faction2'), ["banned"] = false },
    { ['name'] = "faction3", ['hash'] = GetHashKey('faction3'), ["banned"] = false },
    { ['name'] = "ellie", ['hash'] = GetHashKey('ellie'), ["banned"] = false },
    { ['name'] = "gauntlet", ['hash'] = GetHashKey('gauntlet'), ["banned"] = false },
    { ['name'] = "gauntlet2", ['hash'] = GetHashKey('gauntlet2'), ["banned"] = false },
    { ['name'] = "gauntlet3", ['hash'] = GetHashKey('gauntlet3'), ["banned"] = false },
    { ['name'] = "gauntlet4", ['hash'] = GetHashKey('gauntlet4'), ["banned"] = false },
    { ['name'] = "gauntlet5", ['hash'] = GetHashKey('gauntlet5'), ["banned"] = false },
    { ['name'] = "hermes", ['hash'] = GetHashKey('hermes'), ["banned"] = false },
    { ['name'] = "hotknife", ['hash'] = GetHashKey('hotknife'), ["banned"] = false },
    { ['name'] = "hustler", ['hash'] = GetHashKey('hustler'), ["banned"] = false },
    { ['name'] = "impaler", ['hash'] = GetHashKey('impaler'), ["banned"] = false },
    { ['name'] = "impaler2", ['hash'] = GetHashKey('impaler2'), ["banned"] = false },
    { ['name'] = "impaler3", ['hash'] = GetHashKey('impaler3'), ["banned"] = false },
    { ['name'] = "impaler4", ['hash'] = GetHashKey('impaler4'), ["banned"] = false },
    { ['name'] = "imperator", ['hash'] = GetHashKey('imperator'), ["banned"] = false },
    { ['name'] = "imperator2", ['hash'] = GetHashKey('imperator2'), ["banned"] = false },
    { ['name'] = "imperator3", ['hash'] = GetHashKey('imperator3'), ["banned"] = false },
    { ['name'] = "lurcher", ['hash'] = GetHashKey('lurcher'), ["banned"] = false },
    { ['name'] = "moonbeam", ['hash'] = GetHashKey('moonbeam'), ["banned"] = false },
    { ['name'] = "moonbeam2", ['hash'] = GetHashKey('moonbeam2'), ["banned"] = false },
    { ['name'] = "nightshade", ['hash'] = GetHashKey('nightshade'), ["banned"] = false },
    { ['name'] = "peyote2", ['hash'] = GetHashKey('peyote2'), ["banned"] = false },
    { ['name'] = "phoenix", ['hash'] = GetHashKey('phoenix'), ["banned"] = false },
    { ['name'] = "picador", ['hash'] = GetHashKey('picador'), ["banned"] = false },
    { ['name'] = "ratloader", ['hash'] = GetHashKey('ratloader'), ["banned"] = false },
    { ['name'] = "ratloader2", ['hash'] = GetHashKey('ratloader2'), ["banned"] = false },
    { ['name'] = "ruiner", ['hash'] = GetHashKey('ruiner'), ["banned"] = false },
    { ['name'] = "ruiner2", ['hash'] = GetHashKey('ruiner2'), ["banned"] = false },
    { ['name'] = "ruiner3", ['hash'] = GetHashKey('ruiner3'), ["banned"] = false },
    { ['name'] = "sabregt", ['hash'] = GetHashKey('sabregt'), ["banned"] = false },
    { ['name'] = "sabregt2", ['hash'] = GetHashKey('sabregt2'), ["banned"] = false },
    { ['name'] = "slamvan", ['hash'] = GetHashKey('slamvan'), ["banned"] = false },
    { ['name'] = "slamvan2", ['hash'] = GetHashKey('slamvan2'), ["banned"] = false },
    { ['name'] = "slamvan3", ['hash'] = GetHashKey('slamvan3'), ["banned"] = false },
    { ['name'] = "slamvan4", ['hash'] = GetHashKey('slamvan4'), ["banned"] = false },
    { ['name'] = "slamvan5", ['hash'] = GetHashKey('slamvan5'), ["banned"] = false },
    { ['name'] = "slamvan6", ['hash'] = GetHashKey('slamvan6'), ["banned"] = false },
    { ['name'] = "stalion", ['hash'] = GetHashKey('stalion'), ["banned"] = false },
    { ['name'] = "stalion2", ['hash'] = GetHashKey('stalion2'), ["banned"] = false },
    { ['name'] = "tampa", ['hash'] = GetHashKey('tampa'), ["banned"] = false },
    { ['name'] = "tampa3", ['hash'] = GetHashKey('tampa3'), ["banned"] = false },
    { ['name'] = "tulip", ['hash'] = GetHashKey('tulip'), ["banned"] = false },
    { ['name'] = "vamos", ['hash'] = GetHashKey('vamos'), ["banned"] = false },
    { ['name'] = "vigero", ['hash'] = GetHashKey('vigero'), ["banned"] = false },
    { ['name'] = "virgo", ['hash'] = GetHashKey('virgo'), ["banned"] = false },
    { ['name'] = "virgo2", ['hash'] = GetHashKey('virgo2'), ["banned"] = false },
    { ['name'] = "virgo3", ['hash'] = GetHashKey('virgo3'), ["banned"] = false },
    { ['name'] = "voodoo", ['hash'] = GetHashKey('voodoo'), ["banned"] = false },
    { ['name'] = "voodoo2", ['hash'] = GetHashKey('voodoo2'), ["banned"] = false },
    { ['name'] = "yosemite", ['hash'] = GetHashKey('yosemite'), ["banned"] = false },
    { ['name'] = "yosemite2", ['hash'] = GetHashKey('yosemite2'), ["banned"] = false },
    { ['name'] = "yosemite3", ['hash'] = GetHashKey('yosemite3'), ["banned"] = false },
    -- Off-Road
    { ['name'] = "bfinjection", ['hash'] = GetHashKey('bfinjection'), ["banned"] = false },
    { ['name'] = "bifta", ['hash'] = GetHashKey('bifta'), ["banned"] = false },
    { ['name'] = "blazer", ['hash'] = GetHashKey('blazer'), ["banned"] = false },
    { ['name'] = "blazer2", ['hash'] = GetHashKey('blazer2'), ["banned"] = false },
    { ['name'] = "blazer3", ['hash'] = GetHashKey('blazer3'), ["banned"] = false },
    { ['name'] = "blazer4", ['hash'] = GetHashKey('blazer4'), ["banned"] = false },
    { ['name'] = "blazer5", ['hash'] = GetHashKey('blazer5'), ["banned"] = false },
    { ['name'] = "bodhi2", ['hash'] = GetHashKey('bodhi2'), ["banned"] = false },
    { ['name'] = "brawler", ['hash'] = GetHashKey('brawler'), ["banned"] = false },
    { ['name'] = "bruiser", ['hash'] = GetHashKey('bruiser'), ["banned"] = false },
    { ['name'] = "bruiser2", ['hash'] = GetHashKey('bruiser2'), ["banned"] = false },
    { ['name'] = "bruiser3", ['hash'] = GetHashKey('bruiser3'), ["banned"] = false },
    { ['name'] = "brutus", ['hash'] = GetHashKey('brutus'), ["banned"] = false },
    { ['name'] = "brutus2", ['hash'] = GetHashKey('brutus2'), ["banned"] = false },
    { ['name'] = "brutus3", ['hash'] = GetHashKey('brutus3'), ["banned"] = false },
    { ['name'] = "caracara", ['hash'] = GetHashKey('caracara'), ["banned"] = false },
    { ['name'] = "caracara2", ['hash'] = GetHashKey('caracara2'), ["banned"] = false },
    { ['name'] = "dloader", ['hash'] = GetHashKey('dloader'), ["banned"] = false },
    { ['name'] = "dubsta3", ['hash'] = GetHashKey('dubsta3'), ["banned"] = false },
    { ['name'] = "dune", ['hash'] = GetHashKey('dune'), ["banned"] = false },
    { ['name'] = "dune2", ['hash'] = GetHashKey('dune2'), ["banned"] = false },
    { ['name'] = "dune3", ['hash'] = GetHashKey('dune3'), ["banned"] = false },
    { ['name'] = "dune4", ['hash'] = GetHashKey('dune4'), ["banned"] = false },
    { ['name'] = "dune5", ['hash'] = GetHashKey('dune5'), ["banned"] = false },
    { ['name'] = "everon", ['hash'] = GetHashKey('everon'), ["banned"] = false },
    { ['name'] = "freecrawler", ['hash'] = GetHashKey('freecrawler'), ["banned"] = false },
    { ['name'] = "hellion", ['hash'] = GetHashKey('hellion'), ["banned"] = false },
    { ['name'] = "insurgent", ['hash'] = GetHashKey('insurgent'), ["banned"] = false },
    { ['name'] = "insurgent2", ['hash'] = GetHashKey('insurgent2'), ["banned"] = false },
    { ['name'] = "insurgent3", ['hash'] = GetHashKey('insurgent3'), ["banned"] = false },
    { ['name'] = "kalahari", ['hash'] = GetHashKey('kalahari'), ["banned"] = false },
    { ['name'] = "kamacho", ['hash'] = GetHashKey('kamacho'), ["banned"] = false },
    { ['name'] = "marshall", ['hash'] = GetHashKey('marshall'), ["banned"] = false },
    { ['name'] = "mesa3", ['hash'] = GetHashKey('mesa3'), ["banned"] = false },
    { ['name'] = "monster", ['hash'] = GetHashKey('monster'), ["banned"] = false },
    { ['name'] = "monster3", ['hash'] = GetHashKey('monster3'), ["banned"] = false },
    { ['name'] = "monster4", ['hash'] = GetHashKey('monster4'), ["banned"] = false },
    { ['name'] = "monster5", ['hash'] = GetHashKey('monster5'), ["banned"] = false },
    { ['name'] = "menacer", ['hash'] = GetHashKey('menacer'), ["banned"] = false },
    { ['name'] = "outlaw", ['hash'] = GetHashKey('outlaw'), ["banned"] = false },
    { ['name'] = "nightshark", ['hash'] = GetHashKey('nightshark'), ["banned"] = false },
    { ['name'] = "rancherxl", ['hash'] = GetHashKey('rancherxl'), ["banned"] = false },
    { ['name'] = "rancherxl2", ['hash'] = GetHashKey('rancherxl2'), ["banned"] = false },
    { ['name'] = "rebel", ['hash'] = GetHashKey('rebel'), ["banned"] = false },
    { ['name'] = "rebel2", ['hash'] = GetHashKey('rebel2'), ["banned"] = false },
    { ['name'] = "rcbandito", ['hash'] = GetHashKey('rcbandito'), ["banned"] = false },
    { ['name'] = "riata", ['hash'] = GetHashKey('riata'), ["banned"] = false },
    { ['name'] = "sandking", ['hash'] = GetHashKey('sandking'), ["banned"] = false },
    { ['name'] = "sandking2", ['hash'] = GetHashKey('sandking2'), ["banned"] = false },
    { ['name'] = "technical", ['hash'] = GetHashKey('technical'), ["banned"] = false },
    { ['name'] = "technical2", ['hash'] = GetHashKey('technical2'), ["banned"] = false },
    { ['name'] = "technical3", ['hash'] = GetHashKey('technical3'), ["banned"] = false },
    { ['name'] = "trophytruck", ['hash'] = GetHashKey('trophytruck'), ["banned"] = false },
    { ['name'] = "trophytruck2", ['hash'] = GetHashKey('trophytruck2'), ["banned"] = false },
    { ['name'] = "vagrant", ['hash'] = GetHashKey('vagrant'), ["banned"] = false },
    { ['name'] = "zhaba", ['hash'] = GetHashKey('zhaba'), ["banned"] = false },
    { ['name'] = "verus", ['hash'] = GetHashKey('verus'), ["banned"] = false },
    { ['name'] = "winky", ['hash'] = GetHashKey('winky'), ["banned"] = false },
    -- Open Wheel = Fórmula 1
    { ['name'] = "formula", ['hash'] = GetHashKey('formula'), ["banned"] = false },
    { ['name'] = "formula2", ['hash'] = GetHashKey('formula2'), ["banned"] = false },
    { ['name'] = "openwheel1", ['hash'] = GetHashKey('openwheel1'), ["banned"] = false },
    { ['name'] = "openwheel2", ['hash'] = GetHashKey('openwheel2'), ["banned"] = false },
    -- Planes = Aviões
    { ['name'] = "alphaz1", ['hash'] = GetHashKey('alphaz1'), ["banned"] = false },
    { ['name'] = "avenger", ['hash'] = GetHashKey('avenger'), ["banned"] = false },
    { ['name'] = "avenger2", ['hash'] = GetHashKey('avenger2'), ["banned"] = false },
    { ['name'] = "besra", ['hash'] = GetHashKey('besra'), ["banned"] = false },
    { ['name'] = "blimp", ['hash'] = GetHashKey('blimp'), ["banned"] = false },
    { ['name'] = "blimp2", ['hash'] = GetHashKey('blimp2'), ["banned"] = false },
    { ['name'] = "blimp3", ['hash'] = GetHashKey('blimp3'), ["banned"] = false },
    { ['name'] = "bombushka", ['hash'] = GetHashKey('bombushka'), ["banned"] = false },
    { ['name'] = "cargoplane", ['hash'] = GetHashKey('cargoplane'), ["banned"] = false },
    { ['name'] = "cuban800", ['hash'] = GetHashKey('cuban800'), ["banned"] = false },
    { ['name'] = "dodo", ['hash'] = GetHashKey('dodo'), ["banned"] = false },
    { ['name'] = "duster", ['hash'] = GetHashKey('duster'), ["banned"] = false },
    { ['name'] = "howard", ['hash'] = GetHashKey('howard'), ["banned"] = false },
    { ['name'] = "hydra", ['hash'] = GetHashKey('hydra'), ["banned"] = false },
    { ['name'] = "jet", ['hash'] = GetHashKey('jet'), ["banned"] = false },
    { ['name'] = "lazer", ['hash'] = GetHashKey('lazer'), ["banned"] = false },
    { ['name'] = "luxor", ['hash'] = GetHashKey('luxor'), ["banned"] = false },
    { ['name'] = "luxor2", ['hash'] = GetHashKey('luxor2'), ["banned"] = false },
    { ['name'] = "mammatus", ['hash'] = GetHashKey('mammatus'), ["banned"] = false },
    { ['name'] = "microlight", ['hash'] = GetHashKey('microlight'), ["banned"] = false },
    { ['name'] = "miljet", ['hash'] = GetHashKey('miljet'), ["banned"] = false },
    { ['name'] = "mogul", ['hash'] = GetHashKey('mogul'), ["banned"] = false },
    { ['name'] = "molotok", ['hash'] = GetHashKey('molotok'), ["banned"] = false },
    { ['name'] = "nimbus", ['hash'] = GetHashKey('nimbus'), ["banned"] = false },
    { ['name'] = "nokota", ['hash'] = GetHashKey('nokota'), ["banned"] = false },
    { ['name'] = "pyro", ['hash'] = GetHashKey('pyro'), ["banned"] = false },
    { ['name'] = "rogue", ['hash'] = GetHashKey('rogue'), ["banned"] = false },
    { ['name'] = "seabreeze", ['hash'] = GetHashKey('seabreeze'), ["banned"] = false },
    { ['name'] = "shamal", ['hash'] = GetHashKey('shamal'), ["banned"] = false },
    { ['name'] = "starling", ['hash'] = GetHashKey('starling'), ["banned"] = false },
    { ['name'] = "strikeforce", ['hash'] = GetHashKey('strikeforce'), ["banned"] = false },
    { ['name'] = "stunt", ['hash'] = GetHashKey('stunt'), ["banned"] = false },
    { ['name'] = "titan", ['hash'] = GetHashKey('titan'), ["banned"] = false },
    { ['name'] = "tula", ['hash'] = GetHashKey('tula'), ["banned"] = false },
    { ['name'] = "velum", ['hash'] = GetHashKey('velum'), ["banned"] = false },
    { ['name'] = "velum2", ['hash'] = GetHashKey('velum2'), ["banned"] = false },
    { ['name'] = "vestra", ['hash'] = GetHashKey('vestra'), ["banned"] = false },
    { ['name'] = "volatol", ['hash'] = GetHashKey('volatol'), ["banned"] = false },
    { ['name'] = "alkonost", ['hash'] = GetHashKey('alkonost'), ["banned"] = false },
    -- SUVs = Suvs
    { ['name'] = "baller", ['hash'] = GetHashKey('baller'), ["banned"] = false },
    { ['name'] = "baller2", ['hash'] = GetHashKey('baller2'), ["banned"] = false },
    { ['name'] = "baller3", ['hash'] = GetHashKey('baller3'), ["banned"] = false },
    { ['name'] = "baller4", ['hash'] = GetHashKey('baller4'), ["banned"] = false },
    { ['name'] = "baller5", ['hash'] = GetHashKey('baller5'), ["banned"] = false },
    { ['name'] = "baller6", ['hash'] = GetHashKey('baller6'), ["banned"] = false },
    { ['name'] = "bjxl", ['hash'] = GetHashKey('bjxl'), ["banned"] = false },
    { ['name'] = "cavalcade", ['hash'] = GetHashKey('cavalcade'), ["banned"] = false },
    { ['name'] = "cavalcade2", ['hash'] = GetHashKey('cavalcade2'), ["banned"] = false },
    { ['name'] = "contender", ['hash'] = GetHashKey('contender'), ["banned"] = false },
    { ['name'] = "dubsta", ['hash'] = GetHashKey('dubsta'), ["banned"] = false },
    { ['name'] = "dubsta2", ['hash'] = GetHashKey('dubsta2'), ["banned"] = false },
    { ['name'] = "fq2", ['hash'] = GetHashKey('fq2'), ["banned"] = false },
    { ['name'] = "granger", ['hash'] = GetHashKey('granger'), ["banned"] = false },
    { ['name'] = "gresley", ['hash'] = GetHashKey('gresley'), ["banned"] = false },
    { ['name'] = "habanero", ['hash'] = GetHashKey('habanero'), ["banned"] = false },
    { ['name'] = "huntley", ['hash'] = GetHashKey('huntley'), ["banned"] = false },
    { ['name'] = "landstalker", ['hash'] = GetHashKey('landstalker'), ["banned"] = false },
    { ['name'] = "landstalker2", ['hash'] = GetHashKey('landstalker2'), ["banned"] = false },
    { ['name'] = "mesa", ['hash'] = GetHashKey('mesa'), ["banned"] = false },
    { ['name'] = "mesa2", ['hash'] = GetHashKey('mesa2'), ["banned"] = false },
    { ['name'] = "novak", ['hash'] = GetHashKey('novak'), ["banned"] = false },
    { ['name'] = "patriot", ['hash'] = GetHashKey('patriot'), ["banned"] = false },
    { ['name'] = "patriot2", ['hash'] = GetHashKey('patriot2'), ["banned"] = false },
    { ['name'] = "radi", ['hash'] = GetHashKey('radi'), ["banned"] = false },
    { ['name'] = "rebla", ['hash'] = GetHashKey('rebla'), ["banned"] = false },
    { ['name'] = "rocoto", ['hash'] = GetHashKey('rocoto'), ["banned"] = false },
    { ['name'] = "seminole", ['hash'] = GetHashKey('seminole'), ["banned"] = false },
    { ['name'] = "seminole2", ['hash'] = GetHashKey('seminole2'), ["banned"] = false },
    { ['name'] = "serrano", ['hash'] = GetHashKey('serrano'), ["banned"] = false },
    { ['name'] = "toros", ['hash'] = GetHashKey('toros'), ["banned"] = false },
    { ['name'] = "xls", ['hash'] = GetHashKey('xls'), ["banned"] = false },
    { ['name'] = "xls2", ['hash'] = GetHashKey('xls2'), ["banned"] = false },
    { ['name'] = "squaddie", ['hash'] = GetHashKey('squaddie'), ["banned"] = false },
    -- Sedans
    { ['name'] = "asea", ['hash'] = GetHashKey('asea'), ["banned"] = false },
    { ['name'] = "asea2", ['hash'] = GetHashKey('asea2'), ["banned"] = false },
    { ['name'] = "asterope", ['hash'] = GetHashKey('asterope'), ["banned"] = false },
    { ['name'] = "cog55", ['hash'] = GetHashKey('cog55'), ["banned"] = false },
    { ['name'] = "cog552", ['hash'] = GetHashKey('cog552'), ["banned"] = false },
    { ['name'] = "cognoscenti", ['hash'] = GetHashKey('cognoscenti'), ["banned"] = false },
    { ['name'] = "cognoscenti2", ['hash'] = GetHashKey('cognoscenti2'), ["banned"] = false },
    { ['name'] = "emperor", ['hash'] = GetHashKey('emperor'), ["banned"] = false },
    { ['name'] = "emperor2", ['hash'] = GetHashKey('emperor2'), ["banned"] = false },
    { ['name'] = "emperor3", ['hash'] = GetHashKey('emperor3'), ["banned"] = false },
    { ['name'] = "fugitive", ['hash'] = GetHashKey('fugitive'), ["banned"] = false },
    { ['name'] = "glendale", ['hash'] = GetHashKey('glendale'), ["banned"] = false },
    { ['name'] = "glendale2", ['hash'] = GetHashKey('glendale2'), ["banned"] = false },
    { ['name'] = "ingot", ['hash'] = GetHashKey('ingot'), ["banned"] = false },
    { ['name'] = "intruder", ['hash'] = GetHashKey('intruder'), ["banned"] = false },
    { ['name'] = "limo2", ['hash'] = GetHashKey('limo2'), ["banned"] = false },
    { ['name'] = "premier", ['hash'] = GetHashKey('premier'), ["banned"] = false },
    { ['name'] = "primo", ['hash'] = GetHashKey('primo'), ["banned"] = false },
    { ['name'] = "primo2", ['hash'] = GetHashKey('primo2'), ["banned"] = false },
    { ['name'] = "regina", ['hash'] = GetHashKey('regina'), ["banned"] = false },
    { ['name'] = "romero", ['hash'] = GetHashKey('romero'), ["banned"] = false },
    { ['name'] = "stafford", ['hash'] = GetHashKey('stafford'), ["banned"] = false },
    { ['name'] = "stanier", ['hash'] = GetHashKey('stanier'), ["banned"] = false },
    { ['name'] = "stratum", ['hash'] = GetHashKey('stratum'), ["banned"] = false },
    { ['name'] = "stretch", ['hash'] = GetHashKey('stretch'), ["banned"] = false },
    { ['name'] = "superd", ['hash'] = GetHashKey('superd'), ["banned"] = false },
    { ['name'] = "surge", ['hash'] = GetHashKey('surge'), ["banned"] = false },
    { ['name'] = "tailgater", ['hash'] = GetHashKey('tailgater'), ["banned"] = false },
    { ['name'] = "warrener", ['hash'] = GetHashKey('warrener'), ["banned"] = false },
    { ['name'] = "washington", ['hash'] = GetHashKey('washington'), ["banned"] = false },
    -- Service = Serviços
    { ['name'] = "airbus", ['hash'] = GetHashKey('airbus'), ["banned"] = false },
    { ['name'] = "brickade", ['hash'] = GetHashKey('brickade'), ["banned"] = false },
    { ['name'] = "bus", ['hash'] = GetHashKey('bus'), ["banned"] = false },
    { ['name'] = "coach", ['hash'] = GetHashKey('coach'), ["banned"] = false },
    { ['name'] = "pbus2", ['hash'] = GetHashKey('pbus2'), ["banned"] = false },
    { ['name'] = "rallytruck", ['hash'] = GetHashKey('rallytruck'), ["banned"] = false },
    { ['name'] = "rentalbus", ['hash'] = GetHashKey('rentalbus'), ["banned"] = false },
    { ['name'] = "taxi", ['hash'] = GetHashKey('taxi'), ["banned"] = false },
    { ['name'] = "tourbus", ['hash'] = GetHashKey('tourbus'), ["banned"] = false },
    { ['name'] = "trash", ['hash'] = GetHashKey('trash'), ["banned"] = false },
    { ['name'] = "trash2", ['hash'] = GetHashKey('trash2'), ["banned"] = false },
    { ['name'] = "wastelander", ['hash'] = GetHashKey('wastelander'), ["banned"] = false },
    -- Sports = Esportivos
    { ['name'] = "alpha", ['hash'] = GetHashKey('alpha'), ["banned"] = false },
    { ['name'] = "banshee", ['hash'] = GetHashKey('banshee'), ["banned"] = false },
    { ['name'] = "bestiagts", ['hash'] = GetHashKey('bestiagts'), ["banned"] = false },
    { ['name'] = "blista2", ['hash'] = GetHashKey('blista2'), ["banned"] = false },
    { ['name'] = "blista3", ['hash'] = GetHashKey('blista3'), ["banned"] = false },
    { ['name'] = "buffalo", ['hash'] = GetHashKey('buffalo'), ["banned"] = false },
    { ['name'] = "buffalo2", ['hash'] = GetHashKey('buffalo2'), ["banned"] = false },
    { ['name'] = "buffalo3", ['hash'] = GetHashKey('buffalo3'), ["banned"] = false },
    { ['name'] = "carbonizzare", ['hash'] = GetHashKey('carbonizzare'), ["banned"] = false },
    { ['name'] = "comet2", ['hash'] = GetHashKey('comet2'), ["banned"] = false },
    { ['name'] = "comet3", ['hash'] = GetHashKey('comet3'), ["banned"] = false },
    { ['name'] = "comet4", ['hash'] = GetHashKey('comet4'), ["banned"] = false },
    { ['name'] = "comet5", ['hash'] = GetHashKey('comet5'), ["banned"] = false },
    { ['name'] = "coquette", ['hash'] = GetHashKey('coquette'), ["banned"] = false },
    { ['name'] = "coquette4", ['hash'] = GetHashKey('coquette4'), ["banned"] = false },
    { ['name'] = "drafter", ['hash'] = GetHashKey('drafter'), ["banned"] = false },
    { ['name'] = "deveste", ['hash'] = GetHashKey('deveste'), ["banned"] = false },
    { ['name'] = "elegy", ['hash'] = GetHashKey('elegy'), ["banned"] = false },
    { ['name'] = "elegy2", ['hash'] = GetHashKey('elegy2'), ["banned"] = false },
    { ['name'] = "feltzer2", ['hash'] = GetHashKey('feltzer2'), ["banned"] = false },
    { ['name'] = "flashgt", ['hash'] = GetHashKey('flashgt'), ["banned"] = false },
    { ['name'] = "furoregt", ['hash'] = GetHashKey('furoregt'), ["banned"] = false },
    { ['name'] = "fusilade", ['hash'] = GetHashKey('fusilade'), ["banned"] = false },
    { ['name'] = "futo", ['hash'] = GetHashKey('futo'), ["banned"] = false },
    { ['name'] = "gb200", ['hash'] = GetHashKey('gb200'), ["banned"] = false },
    { ['name'] = "hotring", ['hash'] = GetHashKey('hotring'), ["banned"] = false },
    { ['name'] = "komoda", ['hash'] = GetHashKey('komoda'), ["banned"] = false },
    { ['name'] = "imorgon", ['hash'] = GetHashKey('imorgon'), ["banned"] = false },
    { ['name'] = "issi7", ['hash'] = GetHashKey('issi7'), ["banned"] = false },
    { ['name'] = "jugular", ['hash'] = GetHashKey('jugular'), ["banned"] = false },
    { ['name'] = "jester", ['hash'] = GetHashKey('jester'), ["banned"] = false },
    { ['name'] = "jester2", ['hash'] = GetHashKey('jester2'), ["banned"] = false },
    { ['name'] = "jester3", ['hash'] = GetHashKey('jester3'), ["banned"] = false },
    { ['name'] = "khamelion", ['hash'] = GetHashKey('khamelion'), ["banned"] = false },
    { ['name'] = "kuruma", ['hash'] = GetHashKey('kuruma'), ["banned"] = false },
    { ['name'] = "kuruma2", ['hash'] = GetHashKey('kuruma2'), ["banned"] = false },
    { ['name'] = "locust", ['hash'] = GetHashKey('locust'), ["banned"] = false },
    { ['name'] = "lynx", ['hash'] = GetHashKey('lynx'), ["banned"] = false },
    { ['name'] = "massacro", ['hash'] = GetHashKey('massacro'), ["banned"] = false },
    { ['name'] = "massacro2", ['hash'] = GetHashKey('massacro2'), ["banned"] = false },
    { ['name'] = "neo", ['hash'] = GetHashKey('neo'), ["banned"] = false },
    { ['name'] = "neon", ['hash'] = GetHashKey('neon'), ["banned"] = false },
    { ['name'] = "ninef", ['hash'] = GetHashKey('ninef'), ["banned"] = false },
    { ['name'] = "ninef2", ['hash'] = GetHashKey('ninef2'), ["banned"] = false },
    { ['name'] = "omnis", ['hash'] = GetHashKey('omnis'), ["banned"] = false },
    { ['name'] = "paragon", ['hash'] = GetHashKey('paragon'), ["banned"] = false },
    { ['name'] = "paragon2", ['hash'] = GetHashKey('paragon2'), ["banned"] = false },
    { ['name'] = "pariah", ['hash'] = GetHashKey('pariah'), ["banned"] = false },
    { ['name'] = "penumbra", ['hash'] = GetHashKey('penumbra'), ["banned"] = false },
    { ['name'] = "penumbra2", ['hash'] = GetHashKey('penumbra2'), ["banned"] = false },
    { ['name'] = "raiden", ['hash'] = GetHashKey('raiden'), ["banned"] = false },
    { ['name'] = "rapidgt", ['hash'] = GetHashKey('rapidgt'), ["banned"] = false },
    { ['name'] = "rapidgt2", ['hash'] = GetHashKey('rapidgt2'), ["banned"] = false },
    { ['name'] = "raptor", ['hash'] = GetHashKey('raptor'), ["banned"] = false },
    { ['name'] = "revolter", ['hash'] = GetHashKey('revolter'), ["banned"] = false },
    { ['name'] = "ruston", ['hash'] = GetHashKey('ruston'), ["banned"] = false },
    { ['name'] = "schafter2", ['hash'] = GetHashKey('schafter2'), ["banned"] = false },
    { ['name'] = "schafter3", ['hash'] = GetHashKey('schafter3'), ["banned"] = false },
    { ['name'] = "schafter4", ['hash'] = GetHashKey('schafter4'), ["banned"] = false },
    { ['name'] = "schafter5", ['hash'] = GetHashKey('schafter5'), ["banned"] = false },
    { ['name'] = "schafter6", ['hash'] = GetHashKey('schafter6'), ["banned"] = false },
    { ['name'] = "schlagen", ['hash'] = GetHashKey('schlagen'), ["banned"] = false },
    { ['name'] = "schwarzer", ['hash'] = GetHashKey('schwarzer'), ["banned"] = false },
    { ['name'] = "sentinel3", ['hash'] = GetHashKey('sentinel3'), ["banned"] = false },
    { ['name'] = "seven70", ['hash'] = GetHashKey('seven70'), ["banned"] = false },
    { ['name'] = "specter", ['hash'] = GetHashKey('specter'), ["banned"] = false },
    { ['name'] = "specter2", ['hash'] = GetHashKey('specter2'), ["banned"] = false },
    { ['name'] = "streiter", ['hash'] = GetHashKey('streiter'), ["banned"] = false },
    { ['name'] = "sugoi", ['hash'] = GetHashKey('sugoi'), ["banned"] = false },
    { ['name'] = "sultan", ['hash'] = GetHashKey('sultan'), ["banned"] = false },
    { ['name'] = "sultan2", ['hash'] = GetHashKey('sultan2'), ["banned"] = false },
    { ['name'] = "surano", ['hash'] = GetHashKey('surano'), ["banned"] = false },
    { ['name'] = "tampa2", ['hash'] = GetHashKey('tampa2'), ["banned"] = false },
    { ['name'] = "tropos", ['hash'] = GetHashKey('tropos'), ["banned"] = false },
    { ['name'] = "verlierer2", ['hash'] = GetHashKey('verlierer2'), ["banned"] = false },
    { ['name'] = "vstr", ['hash'] = GetHashKey('vstr'), ["banned"] = false },
    { ['name'] = "zr380", ['hash'] = GetHashKey('zr380'), ["banned"] = false },
    { ['name'] = "zr3802", ['hash'] = GetHashKey('zr3802'), ["banned"] = false },
    { ['name'] = "zr3803", ['hash'] = GetHashKey('zr3803'), ["banned"] = false },
    { ['name'] = "italirsx", ['hash'] = GetHashKey('italirsx'), ["banned"] = false },
    { ['name'] = "veto", ['hash'] = GetHashKey('veto'), ["banned"] = false },
    { ['name'] = "veto2", ['hash'] = GetHashKey('veto2'), ["banned"] = false },
    -- Sports Classic = Esportivos Clássicos
    { ['name'] = "ardent", ['hash'] = GetHashKey('ardent'), ["banned"] = false },
    { ['name'] = "btype", ['hash'] = GetHashKey('btype'), ["banned"] = false },
    { ['name'] = "btype2", ['hash'] = GetHashKey('btype2'), ["banned"] = false },
    { ['name'] = "btype3", ['hash'] = GetHashKey('btype3'), ["banned"] = false },
    { ['name'] = "casco", ['hash'] = GetHashKey('casco'), ["banned"] = false },
    { ['name'] = "cheetah2", ['hash'] = GetHashKey('cheetah2'), ["banned"] = false },
    { ['name'] = "coquette2", ['hash'] = GetHashKey('coquette2'), ["banned"] = false },
    { ['name'] = "deluxo", ['hash'] = GetHashKey('deluxo'), ["banned"] = false },
    { ['name'] = "dynasty", ['hash'] = GetHashKey('dynasty'), ["banned"] = false },
    { ['name'] = "fagaloa", ['hash'] = GetHashKey('fagaloa'), ["banned"] = false },
    { ['name'] = "feltzer3", ['hash'] = GetHashKey('feltzer3'), ["banned"] = false },
    { ['name'] = "gt500", ['hash'] = GetHashKey('gt500'), ["banned"] = false },
    { ['name'] = "infernus2", ['hash'] = GetHashKey('infernus2'), ["banned"] = false },
    { ['name'] = "jb700", ['hash'] = GetHashKey('jb700'), ["banned"] = false },
    { ['name'] = "jb7002", ['hash'] = GetHashKey('jb7002'), ["banned"] = false },
    { ['name'] = "mamba", ['hash'] = GetHashKey('mamba'), ["banned"] = false },
    { ['name'] = "manana", ['hash'] = GetHashKey('manana'), ["banned"] = false },
    { ['name'] = "manana2", ['hash'] = GetHashKey('manana2'), ["banned"] = false },
    { ['name'] = "michelli", ['hash'] = GetHashKey('michelli'), ["banned"] = false },
    { ['name'] = "monroe", ['hash'] = GetHashKey('monroe'), ["banned"] = false },
    { ['name'] = "nebula", ['hash'] = GetHashKey('nebula'), ["banned"] = false },
    { ['name'] = "peyote", ['hash'] = GetHashKey('peyote'), ["banned"] = false },
    { ['name'] = "peyote3", ['hash'] = GetHashKey('peyote3'), ["banned"] = false },
    { ['name'] = "pigalle", ['hash'] = GetHashKey('pigalle'), ["banned"] = false },
    { ['name'] = "rapidgt3", ['hash'] = GetHashKey('rapidgt3'), ["banned"] = false },
    { ['name'] = "retinue", ['hash'] = GetHashKey('retinue'), ["banned"] = false },
    { ['name'] = "retinue2", ['hash'] = GetHashKey('retinue2'), ["banned"] = false },
    { ['name'] = "savestra", ['hash'] = GetHashKey('savestra'), ["banned"] = false },
    { ['name'] = "stinger", ['hash'] = GetHashKey('stinger'), ["banned"] = false },
    { ['name'] = "stingergt", ['hash'] = GetHashKey('stingergt'), ["banned"] = false },
    { ['name'] = "stromberg", ['hash'] = GetHashKey('stromberg'), ["banned"] = false },
    { ['name'] = "swinger", ['hash'] = GetHashKey('swinger'), ["banned"] = false },
    { ['name'] = "torero", ['hash'] = GetHashKey('torero'), ["banned"] = false },
    { ['name'] = "tornado", ['hash'] = GetHashKey('tornado'), ["banned"] = false },
    { ['name'] = "tornado2", ['hash'] = GetHashKey('tornado2'), ["banned"] = false },
    { ['name'] = "tornado3", ['hash'] = GetHashKey('tornado3'), ["banned"] = false },
    { ['name'] = "tornado4", ['hash'] = GetHashKey('tornado4'), ["banned"] = false },
    { ['name'] = "tornado5", ['hash'] = GetHashKey('tornado5'), ["banned"] = false },
    { ['name'] = "tornado6", ['hash'] = GetHashKey('tornado6'), ["banned"] = false },
    { ['name'] = "turismo2", ['hash'] = GetHashKey('turismo2'), ["banned"] = false },
    { ['name'] = "viseris", ['hash'] = GetHashKey('viseris'), ["banned"] = false },
    { ['name'] = "z190", ['hash'] = GetHashKey('z190'), ["banned"] = false },
    { ['name'] = "ztype", ['hash'] = GetHashKey('ztype'), ["banned"] = false },
    { ['name'] = "zion3", ['hash'] = GetHashKey('zion3'), ["banned"] = false },
    { ['name'] = "cheburek", ['hash'] = GetHashKey('cheburek'), ["banned"] = false },
    { ['name'] = "toreador", ['hash'] = GetHashKey('toreador'), ["banned"] = false },
    -- Super
    { ['name'] = "adder", ['hash'] = GetHashKey('adder'), ["banned"] = false },
    { ['name'] = "autarch", ['hash'] = GetHashKey('autarch'), ["banned"] = false },
    { ['name'] = "banshee2", ['hash'] = GetHashKey('banshee2'), ["banned"] = false },
    { ['name'] = "bullet", ['hash'] = GetHashKey('bullet'), ["banned"] = false },
    { ['name'] = "cheetah", ['hash'] = GetHashKey('cheetah'), ["banned"] = false },
    { ['name'] = "cyclone", ['hash'] = GetHashKey('cyclone'), ["banned"] = false },
    { ['name'] = "entity2", ['hash'] = GetHashKey('entity2'), ["banned"] = false },
    { ['name'] = "entityxf", ['hash'] = GetHashKey('entityxf'), ["banned"] = false },
    { ['name'] = "emerus", ['hash'] = GetHashKey('emerus'), ["banned"] = false },
    { ['name'] = "fmj", ['hash'] = GetHashKey('fmj'), ["banned"] = false },
    { ['name'] = "furia", ['hash'] = GetHashKey('furia'), ["banned"] = false },
    { ['name'] = "gp1", ['hash'] = GetHashKey('gp1'), ["banned"] = false },
    { ['name'] = "infernus", ['hash'] = GetHashKey('infernus'), ["banned"] = false },
    { ['name'] = "italigtb", ['hash'] = GetHashKey('italigtb'), ["banned"] = false },
    { ['name'] = "italigtb2", ['hash'] = GetHashKey('italigtb2'), ["banned"] = false },
    { ['name'] = "krieger", ['hash'] = GetHashKey('krieger'), ["banned"] = false },
    { ['name'] = "le7b", ['hash'] = GetHashKey('le7b'), ["banned"] = false },
    { ['name'] = "nero", ['hash'] = GetHashKey('nero'), ["banned"] = false },
    { ['name'] = "nero2", ['hash'] = GetHashKey('nero2'), ["banned"] = false },
    { ['name'] = "osiris", ['hash'] = GetHashKey('osiris'), ["banned"] = false },
    { ['name'] = "penetrator", ['hash'] = GetHashKey('penetrator'), ["banned"] = false },
    { ['name'] = "pfister811", ['hash'] = GetHashKey('pfister811'), ["banned"] = false },
    { ['name'] = "pfister811", ['hash'] = GetHashKey('pfister811'), ["banned"] = false },
    { ['name'] = "reaper", ['hash'] = GetHashKey('reaper'), ["banned"] = false },
    { ['name'] = "s80", ['hash'] = GetHashKey('s80'), ["banned"] = false },
    { ['name'] = "sc1", ['hash'] = GetHashKey('sc1'), ["banned"] = false },
    { ['name'] = "scramjet", ['hash'] = GetHashKey('scramjet'), ["banned"] = false },
    { ['name'] = "sheava", ['hash'] = GetHashKey('sheava'), ["banned"] = false },
    { ['name'] = "sultanrs", ['hash'] = GetHashKey('sultanrs'), ["banned"] = false },
    { ['name'] = "t20", ['hash'] = GetHashKey('t20'), ["banned"] = false },
    { ['name'] = "taipan", ['hash'] = GetHashKey('taipan'), ["banned"] = false },
    { ['name'] = "tempesta", ['hash'] = GetHashKey('tempesta'), ["banned"] = false },
    { ['name'] = "tezeract", ['hash'] = GetHashKey('tezeract'), ["banned"] = false },
    { ['name'] = "thrax", ['hash'] = GetHashKey('thrax'), ["banned"] = false },
    { ['name'] = "tigon", ['hash'] = GetHashKey('tigon'), ["banned"] = false },
    { ['name'] = "turismor", ['hash'] = GetHashKey('turismor'), ["banned"] = false },
    { ['name'] = "tyrant", ['hash'] = GetHashKey('tyrant'), ["banned"] = false },
    { ['name'] = "tyrus", ['hash'] = GetHashKey('tyrus'), ["banned"] = false },
    { ['name'] = "vacca", ['hash'] = GetHashKey('vacca'), ["banned"] = false },
    { ['name'] = "vagner", ['hash'] = GetHashKey('vagner'), ["banned"] = false },
    { ['name'] = "vigilante", ['hash'] = GetHashKey('vigilante'), ["banned"] = false },
    { ['name'] = "visione", ['hash'] = GetHashKey('visione'), ["banned"] = false },
    { ['name'] = "voltic", ['hash'] = GetHashKey('voltic'), ["banned"] = false },
    { ['name'] = "voltic2", ['hash'] = GetHashKey('voltic2'), ["banned"] = false },
    { ['name'] = "xa21", ['hash'] = GetHashKey('xa21'), ["banned"] = false },
    { ['name'] = "zentorno", ['hash'] = GetHashKey('zentorno'), ["banned"] = false },
    { ['name'] = "zorrusso", ['hash'] = GetHashKey('zorrusso'), ["banned"] = false },
    { ['name'] = "airtug", ['hash'] = GetHashKey('airtug'), ["banned"] = false },
    { ['name'] = "caddy", ['hash'] = GetHashKey('caddy'), ["banned"] = false },
    { ['name'] = "caddy2", ['hash'] = GetHashKey('caddy2'), ["banned"] = false },
    { ['name'] = "caddy3", ['hash'] = GetHashKey('caddy3'), ["banned"] = false },
    { ['name'] = "docktug", ['hash'] = GetHashKey('docktug'), ["banned"] = false },
    { ['name'] = "forklift", ['hash'] = GetHashKey('forklift'), ["banned"] = false },
    { ['name'] = "mower", ['hash'] = GetHashKey('mower'), ["banned"] = false },
    { ['name'] = "ripley", ['hash'] = GetHashKey('ripley'), ["banned"] = false },
    { ['name'] = "sadler", ['hash'] = GetHashKey('sadler'), ["banned"] = false },
    { ['name'] = "sadler2", ['hash'] = GetHashKey('sadler2'), ["banned"] = false },
    { ['name'] = "scrap", ['hash'] = GetHashKey('scrap'), ["banned"] = false },
    { ['name'] = "towtruck", ['hash'] = GetHashKey('towtruck'), ["banned"] = false },
    { ['name'] = "towtruck2", ['hash'] = GetHashKey('towtruck2'), ["banned"] = false },
    { ['name'] = "tractor", ['hash'] = GetHashKey('tractor'), ["banned"] = false },
    { ['name'] = "tractor2", ['hash'] = GetHashKey('tractor2'), ["banned"] = false },
    { ['name'] = "tractor3", ['hash'] = GetHashKey('tractor3'), ["banned"] = false },
    { ['name'] = "utillitruck", ['hash'] = GetHashKey('utillitruck'), ["banned"] = false },
    { ['name'] = "utillitruck2", ['hash'] = GetHashKey('utillitruck2'), ["banned"] = false },
    { ['name'] = "utillitruck3", ['hash'] = GetHashKey('utillitruck3'), ["banned"] = false },
    { ['name'] = "slamtruck", ['hash'] = GetHashKey(''), ["banned"] = false },
    { ['name'] = "bison", ['hash'] = GetHashKey('bison'), ["banned"] = false },
    { ['name'] = "bison2", ['hash'] = GetHashKey('bison2'), ["banned"] = false },
    { ['name'] = "bison3", ['hash'] = GetHashKey('bison3'), ["banned"] = false },
    { ['name'] = "bobcatxl", ['hash'] = GetHashKey('bobcatxl'), ["banned"] = false },
    { ['name'] = "boxville", ['hash'] = GetHashKey('boxville'), ["banned"] = false },
    { ['name'] = "boxville2", ['hash'] = GetHashKey('boxville2'), ["banned"] = false },
    { ['name'] = "boxville3", ['hash'] = GetHashKey('boxville3'), ["banned"] = false },
    { ['name'] = "boxville4", ['hash'] = GetHashKey('boxville4'), ["banned"] = false },
    { ['name'] = "boxville5", ['hash'] = GetHashKey('boxville5'), ["banned"] = false },
    { ['name'] = "burrito", ['hash'] = GetHashKey('burrito'), ["banned"] = false },
    { ['name'] = "burrito2", ['hash'] = GetHashKey('burrito2'), ["banned"] = false },
    { ['name'] = "burrito3", ['hash'] = GetHashKey('burrito3'), ["banned"] = false },
    { ['name'] = "burrito4", ['hash'] = GetHashKey('burrito4'), ["banned"] = false },
    { ['name'] = "burrito5", ['hash'] = GetHashKey('burrito5'), ["banned"] = false },
    { ['name'] = "camper", ['hash'] = GetHashKey('camper'), ["banned"] = false },
    { ['name'] = "gburrito", ['hash'] = GetHashKey('gburrito'), ["banned"] = false },
    { ['name'] = "gburrito2", ['hash'] = GetHashKey('gburrito2'), ["banned"] = false },
    { ['name'] = "journey", ['hash'] = GetHashKey('journey'), ["banned"] = false },
    { ['name'] = "minivan", ['hash'] = GetHashKey('minivan'), ["banned"] = false },
    { ['name'] = "minivan2", ['hash'] = GetHashKey('minivan2'), ["banned"] = false },
    { ['name'] = "paradise", ['hash'] = GetHashKey('paradise'), ["banned"] = false },
    { ['name'] = "pony", ['hash'] = GetHashKey('pony'), ["banned"] = false },
    { ['name'] = "pony2", ['hash'] = GetHashKey('pony2'), ["banned"] = false },
    { ['name'] = "rumpo", ['hash'] = GetHashKey('rumpo'), ["banned"] = false },
    { ['name'] = "rumpo2", ['hash'] = GetHashKey('rumpo2'), ["banned"] = false },
    { ['name'] = "rumpo3", ['hash'] = GetHashKey('rumpo3'), ["banned"] = false },
    { ['name'] = "speedo", ['hash'] = GetHashKey('speedo'), ["banned"] = false },
    { ['name'] = "speedo2", ['hash'] = GetHashKey('speedo2'), ["banned"] = false },
    { ['name'] = "speedo4", ['hash'] = GetHashKey('speedo4'), ["banned"] = false },
    { ['name'] = "surfer", ['hash'] = GetHashKey('surfer'), ["banned"] = false },
    { ['name'] = "surfer2", ['hash'] = GetHashKey('surfer2'), ["banned"] = false },
    { ['name'] = "taco", ['hash'] = GetHashKey('taco'), ["banned"] = false },
    { ['name'] = "youga", ['hash'] = GetHashKey('youga'), ["banned"] = false },
    { ['name'] = "youga2", ['hash'] = GetHashKey('youga2'), ["banned"] = false },
    { ['name'] = "youga3", ['hash'] = GetHashKey('youga3'), ["banned"] = false },
    -- ADD-ON
   -- { ['name'] = "", ['hash'] = GetHashKey(''), ["banned"] = false },

}

-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehList(radius)
	local ped = PlayerPedId()
	local veh = GetVehiclePedIsUsing(ped)
	if not IsPedInAnyVehicle(ped) then
		veh = tvRP.getNearestVehicle(radius)
	end
	if IsEntityAVehicle(veh) then
		local lock = GetVehicleDoorLockStatus(veh)
		local trunk = GetVehicleDoorAngleRatio(v,5)
		local x,y,z = table.unpack(GetEntityCoords(ped))
		for k,v in pairs(vehList) do
			if v.hash == GetEntityModel(veh) then
				if v.name then
					local tuning = { GetNumVehicleMods(veh,13),GetNumVehicleMods(veh,12),GetNumVehicleMods(veh,15),GetNumVehicleMods(veh,11),GetNumVehicleMods(veh,16) }
					return veh,VehToNet(veh),GetVehicleNumberPlateText(veh),v.name,lock,v.banned,trunk,GetDisplayNameFromVehicleModel(v.name),GetStreetNameFromHashKey(GetStreetNameAtCoord(x,y,z)),tuning
				end
			end
		end
	end
end